name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, widows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Set env
        run: echo "TAG_NAME=$(echo ${{github.ref}} | sed 's/refs\/tags\///g')" >> $GITHUB_ENV
      - name: Distribute
        run: |
          go run -ldflags "-X 'main.netPath=default.nn' -X 'main.Version=$TAG_NAME'" netgen/nn.go
          ext=""
          osName="linux"
          if ${{matrix.os}} == windows-latest; then
            ext=".exe"
            osName="windows"
          fi
          if ${{matrix.os}} == macos-latest; then
            osName="darwin"
          fi
          go build -gcflags -B -o zahak-"$osName"-amd64-$TAG_NAME-avx"$ext" ./...
          if ${{matrix.os}} == ubuntu-latest; then
            echo "soon"
          fi
      - name: Create Release and Upload Assets
        id: create-release-and-upload-asset
        run: |
          set -x
          assets=()
          for asset in zahak-; do
            assets+=("-a" "$asset")
          done
          tag_name="$TAG_NAME"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name" || hub release edit "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
