name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Test
        run: |
          go run -ldflags "-X 'main.netPath=default.nn' -X 'main.Version=$TAG_NAME'" netgen/nn.go
          go test ./...
      - name: Set env
        shell: bash
        run: echo "TAG_NAME=$(echo ${{github.ref}} | sed 's/refs\/tags\///g')" >> $GITHUB_ENV
      - name: Distribute
        shell: bash
        run: |
           if [ "$RUNNER_OS" == "Windows" ]; then
             mkdir bin
             go run -ldflags "-X 'main.netPath=default.nn' -X 'main.Version=$TAG_NAME'" netgen/nn.go
             CGO_ENABLED="1" go build -gcflags -B -o bin ./...; mv bin/zahak.exe bin/zahak-windows-amd64-"$TAG_NAME"-avx.exe
           else
             mkdir bin
             go run -ldflags "-X 'main.netPath=default.nn' -X 'main.Version=$TAG_NAME'" netgen/nn.go
             osName="linux"

             if [[ ${{matrix.os}} == macos-latest ]]; then
               osName="darwin"
             fi
             CGO_ENABLED="1" go build -gcflags -B -o bin ./... && mv bin/zahak bin/zahak-"$osName"-amd64-"$TAG_NAME"-avx
           fi

      - name: Create Release and Upload Assets
        id: create-release-and-upload-asset
        shell: bash
        run: |
          set -x
          assets=()
          for asset in bin/zahak-*; do
            assets+=("-a" "$asset")
          done
          tag_name="$TAG_NAME"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name" || hub release edit "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
