name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Set env
        run: echo "TAG_NAME=$(echo ${{github.ref}} | sed 's/refs\/tags\///g')" >> $GITHUB_ENV
      - name: Distribute
        run: |
          make dist
          mv bin/zahak-linux-amd64 bin/zahak-linux-amd64-"$TAG_NAME"
          mv bin/zahak-linux-arm32 bin/zahak-linux-arm32-"$TAG_NAME"
          mv bin/zahak-linux-arm64 bin/zahak-linux-arm64-"$TAG_NAME"
          mv bin/zahak-darwin-amd64 bin/zahak-darwin-amd64-"$TAG_NAME"
          mv bin/zahak-darwin-m1-arm64 bin/zahak-darwin-m1-arm64-"$TAG_NAME"
          mv bin/zahak-windows-amd64.exe bin/zahak-windows-amd64-"$TAG_NAME".exe
          mv bin/zahak-windows-386.exe bin/zahak-windows-386-"$TAG_NAME".exe
      - name: Create Release and Upload Assets
        id: create-release-and-upload-asset
        run: |
          set -x
          assets=()
          for asset in bin/zahak-*; do
            assets+=("-a" "$asset")
          done
          tag_name="$TAG_NAME"
          hub release create "${assets[@]}" -m "$tag_name" "$tag_name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
